### ISSUE TITLE
迁移到Realm

### ISSUE THREAD

**Issue by serco-chen** [kanmaoxian/issues#25]
#### 原因

* RN的`AsyncStorage`组件在Android上有6MB的大小限制

#### TODO

* [x] 迁移 local book model
* [x] 迁移 阅读进度 model
* [ ] 迁移 目录 model
* [ ] 迁移 设置 model

**Comment by serco-chen** [comment]
Done.
